version: '3.2'

services:

   postgres:
     container_name: controle-postgres
     image: postgres
     restart: always
     environment:
       POSTGRES_USER: ${DATABASE_USERNAME}
       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
       POSTGRES_DB: ${DATABASE}
     volumes:
       - ./pgdata:/var/lib/postgresql/data
       - ./seeccontrole.sql:/docker-entrypoint-initdb.d/seeccontrole.sql
     ports:
       - 6000:5432
     networks:
      rede-controle:
        ipv4_address: 172.20.238.2

   pgadmin:
     container_name: pgadmin_controle
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: "gpd@gmail.com"
       PGADMIN_DEFAULT_PASSWORD: "postgres"
     restart: always
     ports:
       - 5052:80
     depends_on:
       - postgres
     networks:
       rede-controle:
         ipv4_address: 172.20.238.3

   backend:
     container_name: controle
     build:
       context: .
       dockerfile: Dockerfile
     image: controle_backend
     restart: always
     ports:
       - 3030:3030
     depends_on:
       - postgres
     environment:
       - DATABASE_PASSWORD=postgres
     networks:
      rede-controle:
        ipv4_address: 172.20.238.4


networks:
  rede-controle:
    ipam:
      driver: default
      config:
        - subnet: 172.20.238.0/24


