version: '3.9'

networks:
  seec-network:
    name: seec

services:
  controle-postgres:
    container_name: controle
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: controle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgcontrole:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - seec-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d 'controle' -U 'postgres'"]
      interval: 10s
      timeout: 30s
      retries: 10

  contorle-backend:
    container_name: backend-controle
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_controle
    restart: always
    ports:
      - 3030:3030
    networks:
      - seec-network
    depends_on:
      controle-postgres:
        condition: service_healthy




